src/Entity/Home.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HomeRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 */
class Home extends Place
{

    /**
     * @ORM\Column(type="text")
     */
    private $homeAddress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $homeType;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Room", mappedBy="home", orphanRemoval=true)
     */
    private $rooms;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;


    public function __construct()
    {
        $this->rooms = new ArrayCollection();
    }

    public function getOwnerOnYear($year){
        
    }

    public function getHomeNumberAndName(): ?string
    {
        return "( ".$this->getNumber()." ) ".$this->name;
    }

    public function getHomeAddress(): ?string
    {
        return $this->homeAddress;
    }

    public function setHomeAddress(string $homeAddress): self
    {
        $this->homeAddress = $homeAddress;

        return $this;
    }

    public function getHomeType(): ?string
    {
        return $this->homeType;
    }

    public function setHomeType(string $homeType): self
    {
        $this->homeType = $homeType;

        return $this;
    }

    /**
     * @return Collection|Room[]
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): self
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms[] = $room;
            $room->setHome($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): self
    {
        if ($this->rooms->contains($room)) {
            $this->rooms->removeElement($room);
            // set the owning side to null (unless already changed)
            if ($room->getHome() === $this) {
                $room->setHome(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

}

src/Entity/Place.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlaceRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn("place_type")
 * @ORM\DiscriminatorMap({"place" = "Place","home" = "Home","room" = "Room"})
 */
class Place
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $placeId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contract", mappedBy="place", orphanRemoval=true)
     * @ORM\OrderBy({"startDate"="ASC"})
     */
    private $contracts;

    public function __construct()
    {
        $this->contracts = new ArrayCollection();
    }

    public function getPlaceId()
    {
        return $this->placeId;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    
    public function getClass(){

        return ClassUtils::getClass($this);

    }

    /**
     * @return Collection|Contract[]
     */
    public function getContracts(): Collection
    {
        return $this->contracts;
    }

    public function getLastContract()
    {
        return $this->contracts->last();
    }

    public function addContract(Contract $contract): self
    {
        if (!$this->contracts->contains($contract)) {
            $this->contracts[] = $contract;
            $contract->setPlace($this);
        }

        return $this;
    }

    public function removeContract(Contract $contract): self
    {
        if ($this->contracts->contains($contract)) {
            $this->contracts->removeElement($contract);
            // set the owning side to null (unless already changed)
            if ($contract->getPlace() === $this) {
                $contract->setPlace(null);
            }
        }

        return $this;
    }

}

src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Room extends Place
{

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roomType;

    /**
     * @ORM\Column(type="integer")
     */
    private $capacity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Home", inversedBy="rooms")
     * @ORM\JoinColumn(name="home_id", referencedColumnName="place_id",nullable=false)
     * @ORM\JoinColumn(nullable=false)
     */
    private $home;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;


    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getFullRoomAddress(): ?string
    {
        return $this->getNumber()." ,".$this->home->getHomeNumberAndName();
    }


    public function getRoomType(): ?string
    {
        return $this->roomType;
    }

    public function setRoomType(string $roomType): self
    {
        $this->roomType = $roomType;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getOccupantOnYear($year) {
        $currentDate = new \Datetime("now");
        $thirtyDaysLater = clone $currentDate;
        date_modify($thirtyDaysLater,"+60 days");
        $occupants = array();
        $contracts = $this->getContracts();
        foreach ($contracts as $contract) {
            if($contract->getStartDate()->format('Y') == $year && 
               $contract->getEndDate() < $currentDate){
                    array_push($occupants, $contract->getPerson());    
                }
        }

        array_unique($occupants);
        return $occupants;
    }

    public function getOccupant() {
        $currentDate = new \Datetime("now");
        $thirtyDaysLater = clone $currentDate;
        date_modify($thirtyDaysLater,"+60 days");
        $occupants = array();
        $contracts = $this->getContracts();
        foreach ($contracts as $contract) {
            if($contract->getStartDate() < $thirtyDaysLater && $contract->getEndDate() > $currentDate && $contract->getActualEndDate() == null){
                    array_push($occupants, $contract->getPerson());    
                }
        }

        return $occupants;
    }

    public function getCurrentOccupant(){
        $currentDate = new \Datetime("now");
        $thirtyDaysLater = clone $currentDate;
        date_modify($thirtyDaysLater,"+60 days");
        $occupants = array();
        $contracts = $this->getContracts();
        foreach ($contracts as $contract) {
            if($contract->getStartDate() < $thirtyDaysLater && $contract->getEndDate() > $currentDate){
                array_push($occupants, $contract->getPerson());    
            }
        }

        array_unique($occupants);
        return $occupants;
    }

    public function getHome(): ?Home
    {
        return $this->home;
    }

    public function setHome(?Home $home): self
    {
        $this->home = $home;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setRoom($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getRoom() === $this) {
                $transaction->setRoom(null);
            }
        }

        return $this;
    }

}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\RoomRepository;
use App\Repository\PersonRepository;
use App\Repository\TenantRepository;
use App\Repository\TransactionRepository;
use App\Repository\ContractRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class MainController extends Controller
{
    /**
     * @Route("/main", name="main")
     */
    public function index(ContractRepository $contractRepository, TransactionRepository $transactionRepository, RoomRepository $roomRepository,PersonRepository $personRepository): Response
    {	

    	$transactionsPending = $transactionRepository->findBy(
    		[
    			'status'  => 'PENDING',
    		],
    		['dateIssued' => 'DESC']
    	);


        $rooms = $roomRepository->findAll();

        $contractsAboutToExpire = $contractRepository->findAboutToExpire();
        $contractsExpired = $contractRepository->findExpired();
        $contractsNotRenewed = $contractRepository->findNotRenewing();
        $people = $personRepository->findAll();

        return $this->render('main/index.html.twig',[
        	'transactionsPending' => $transactionsPending,
            'contractsAboutToExpire' => $contractsAboutToExpire,
            'contractsExpired' => $contractsExpired,
            'contractsNotRenewed' => $contractsNotRenewed,
            'people' => $people,
            'rooms' => $rooms,
            'main' => true
        ]);
    }

}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paparan Utama{% endblock %}

{% block body %}
<div class="container">
	<br>
  <div class="col-lg-12">
    <h1>Bayaran Tertunggak</h1>

    <table class="table table-responsive clickableRow">
            <thead class="thead-dark">
                <tr>
                    <th>Bilik & Rumah Sewa</th>
                    <th>Butiran Transaksi</th>
                    <th>Amaun Transaksi</th>
                    <th>Status Transaksi</th>
                    <th>Tarikh Dikeluarkan</th>
                    <th>Penerima</th>
                    <th>Pembayar</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactionsPending if (transaction.deletedAt == null and transaction.dateIssued <  date() and transaction.person.deletedAt == null ) %}
                <tr style="color:red" onclick="window.location.assign('{{ path('transaction_show', {'id': transaction.id}) }}')">
                    {%if transaction.person.class == "App\\Entity\\Tenant" %}
                    <td>{{ transaction.person.contracts | last.place.number}}, {{ transaction.person.contracts | last.place.home.HomeNumberAndName }}</td>
                    {% else %}
                    <td>{{ transaction.person.contracts | last.place.HomeNumberAndName }}</td>
                    {% endif %}
                    <td>{{ transaction.transactionDescription }}</td>
                    <td>MYR{{ transaction.transactionAmount }}</td>
                    <td>{{ transaction.status }}</td>
                    <td>{{ transaction.dateIssued ? transaction.dateIssued|date('d-m-Y') : '' }}</td>
                    {% if transaction.transactionType == 'CREDIT' %}
                    <td>{{ transaction.person.icAndName }}</td>
                    {% else %}
                      <td></td>
                    {% endif %}
                    {% if transaction.transactionType == 'DEBIT' %}
                    <td>{{ transaction.person.icAndName }}</td>
                    {% else %}
                      <td></td>
                    {% endif %}
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Tiada Rekod</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
  </div>

 <div class="col-lg-12">
    <h1>Bilik Kosong</h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>No. Bilik</th>
          <th>Kapasiti</th>
          <th>Rumah</th>
        </tr>
      </thead>
      <tbody>
        {% for room in rooms if (room.deletedAt == null) and (room.occupant == false or (room.occupant|length < room.capacity)) %}
          <tr 
          {% if room.currentOccupant|length == room.occupant|length %}
          style="color:red"
          {% else %}
          {% endif %}
            onclick="window.location.assign('{{ path('room_show', {'placeId': room.placeId}) }}')"
          >
            <td>{{ room.number }}</td>
            <td>
            {% if room.occupant != false %} {{ room.occupant | length }} {% else %}0{% endif %}/{{ room.capacity }}
            </td>
            <td>{{ room.home.HomeNumberAndName }}</td>
          </tr>
         {% else %}
                <tr>
                    <td colspan="5">Tiada Rekod</td>
                </tr>
         {% endfor %}
      </tbody>
    </table>
  </div>


  <div class="col-lg-12">
    <h1>Kontrak Yang Akan Tamat</h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Bilik Atau Rumah Sewa</th>
          <th>Nama Pemilik</th>
          <th>Nama Penyewa</th>
          <th>No. Telefon</th>
          <th>Tarikh Kontrak Tamat</th>
        </tr>
      </thead>
      <tbody>
        {% for person in people if person.lastContract != false and person.lastContract.endDate < "now"|date_modify("+30 day") and person.lastContract.actualEndDate == null %}
          <tr style="color:red" onclick="window.location.assign('{{ path('contract_show', {'id': person.lastContract.id}) }}')">
            {% if person.class == "App\\Entity\\Owner" %}
            <td>{{ person.lastContract.place.number }}, {{ person.lastContract.place.homeNumberAndName }} </td>
            {% else %}
            <td>{{ person.lastContract.place.number }}, {{ person.lastContract.place.home.homeNumberAndName }}</td>
            {% endif %}
            {% if person.class == "App\\Entity\\Owner" %}
            <td>{{ person.name }} </td><td></td>
            {% else %}
            <td></td><td>{{ person.name }}</td>
            {% endif %}
            <td>{{ person.telefonNumber }}</td>
            <td>{{ person.lastContract.endDate | date('d-m-Y') }}</td>
          </tr>
         {% else %}
                <tr>
                    <td colspan="5">Tiada Rekod</td>
                </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="col-lg-12">
    <h1>Kontrak Yang Telah Tamat</h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Bilik Atau Rumah Sewa</th>
          <th>Nama Pemilik</th>
          <th>Nama Penyewa</th>
          <th>No. Telefon</th>
          <th>Tarikh Kontrak Tamat</th>
        </tr>
      </thead>
      <tbody>
        {% for person in people if person.lastContract != false and person.lastContract.endDate < date() and person.lastContract.actualEndDate == null %}
          <tr style="color:red" onclick="window.location.assign('{{ path('contract_show', {'id': person.lastContract.id}) }}')">
            {% if person.class == "App\\Entity\\Owner" %}
            <td>{{ person.lastContract.place.number }}, {{ person.lastContract.place.homeNumberAndName }} </td>
            {% else %}
            <td>{{ person.lastContract.place.number }}, {{ person.lastContract.place.home.homeNumberAndName }}</td>
            {% endif %}
            {% if person.class == "App\\Entity\\Owner" %}
            <td>{{ person.name }} </td><td></td>
            {% else %}
            <td></td><td>{{ person.name }}</td>
            {% endif %}
            <td>{{ person.telefonNumber }}</td>
            <td>{{ person.lastContract.endDate | date('d-m-Y') }}</td>
          </tr>
         {% else %}
                <tr>
                    <td colspan="5">Tiada Rekod</td>
                </tr>
            {% endfor %}
      </tbody>
    </table>
  </div>

{% set showTableCount = 0 %}
{% set thirtyDaysLater = 0 %}
{% for contract in contractsNotRenewed %}
 {% set showTable = false %} 
  {% for transaction in contract.person.transactions if transaction.deletedAt == null
    and transaction.status == "PENDING" and contract.person.deletedAt == null and transaction.dateIssued <  date()|date_modify("+30 days") %}
    {% set showTable = true %}
    {% if showTableCount == 0 %}
    <div class="col-lg-12">
      <h1>Pemulangan Deposit</h1>
    </div>
    {% set showTableCount = showTableCount + 1%}
    {% endif %}
  {% endfor %}
  {% if showTable %}
    <div class="col-lg-12">
      {% set total = 0 %}
      <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
          <th>Nama</th>
          <th>Butiran Pembayaran</th>
          <th>Kemasukan</th>
          <th>Pengeluaran</th>
        </tr>
        </thead>
        {% for transaction in contract.person.transactions if transaction.status == "PENDING" %}
          <tr
            style="color:red"
            onclick="window.location.assign('{{ path('transaction_show', {'id': transaction.id}) }}')"
          > 
            <td>{{ contract.person.name }}</td>
            <td>{{ transaction.transactionDescription }}</td>
            {% if transaction.transactionType == "DEBIT" %}
              {% set total = total + transaction.transactionAmount %}
              <td>MYR{{transaction.transactionAmount}}</td>
              <td></td>
            {% else %}
            {% set total = total - transaction.transactionAmount %}
              <td></td>
              <td>MYR{{transaction.transactionAmount}}</td>
            {% endif %}
          </tr>
        {% endfor %}
          <tr>
            <td colspan="2" style="text-align:right">Jumlah</td>
            <td></td>
            {% if total < 0 %}
            <td>MYR{{ total * -1 }}</td>
            {% else %}
            <td style="color:red">-MYR{{ total }}</td>
            {% endif %}
          </tr>
      </table>
    </div>

  {% endif %}

{% endfor %}

</div>
{% endblock %}